//
//  QuestionSet.swift
//  Project2- Quiz Bank
//
//  Created by suhail on 08/09/23.
//

import Foundation

struct QuestionSet{
    
    var questions: [Question] = [
        Question(q: "Which is the largest organ in the human body?", a: ["Heart", "Skin", "Large Intestine"], ca: "Skin"),
        Question(q: "Five dollars is worth how many nickels?", a: ["25", "50", "100"], ca: "100"),
        Question(q: "What do the letters in the GMT time zone stand for?", a: ["Global Meridian Time", "Greenwich Mean Time", "General Median Time"], ca: "Greenwich Mean Time"),
        Question(q: "What is the French word for 'hat'?", a: ["Chapeau", "Écharpe", "Bonnet"], ca: "Chapeau"),
        Question(q: "In past times, what would a gentleman keep in his fob pocket?", a: ["Notebook", "Handkerchief", "Watch"], ca: "Watch"),
        Question(q: "How would one say goodbye in Spanish?", a: ["Au Revoir", "Adiós", "Salir"], ca: "Adiós"),
        Question(q: "Which of these colours is NOT featured in the logo for Google?", a: ["Green", "Orange", "Blue"], ca: "Orange"),
        Question(q: "What alcoholic drink is made from molasses?", a: ["Rum", "Whisky", "Gin"], ca: "Rum"),
        Question(q: "What type of animal was Harambe?", a: ["Panda", "Gorilla", "Crocodile"], ca: "Gorilla"),
        Question(q: "Where is Tasmania located?", a: ["Indonesia", "Australia", "Scotland"], ca: "Australia"),
        Question(q: "Who is the prime minister of india?", a: ["Indonesia", "Australia", "Scotland"], ca: "Australia"),
        Question(q: "What is the capital of France?", a: ["London", "Berlin", "Madrid", "Paris"], ca: "Paris"),
            Question(q: "Which gas do plants absorb from the atmosphere during photosynthesis?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], ca: "Carbon Dioxide"),
            Question(q: "What is the largest planet in our solar system?", a: ["Venus", "Mars", "Jupiter", "Saturn"], ca: "Jupiter"),
            Question(q: "Who wrote the famous play 'Hamlet'?", a: ["Charles Dickens", "Jane Austen", "William Shakespeare", "F. Scott Fitzgerald"], ca: "William Shakespeare"),
            Question(q: "What is the chemical symbol for the element oxygen?", a: ["Ox", "O", "Oy", "Oxg"], ca: "O"),
            Question(q: "How many continents are there on Earth?", a: ["3", "5", "7", "9"], ca: "7"),
            Question(q: "What is the freezing point of water in Fahrenheit?", a: ["0°F", "32°F", "100°F", "212°F"], ca: "32°F"),
            Question(q: "Which planet in our solar system has the most moons?", a: ["Earth", "Mars", "Jupiter", "Saturn"], ca: "Jupiter"),
            Question(q: "Who was the first President of the United States?", a: ["Thomas Jefferson", "John Adams", "George Washington", "Abraham Lincoln"], ca: "George Washington"),
            Question(q: "Which mammal can fly without wings?", a: ["Penguin", "Kangaroo", "Sloth", "Bat"], ca: "Bat"),
            
            Question(q: "What is the largest ocean on Earth?", a: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], ca: "Pacific Ocean"),
            Question(q: "Which gas is responsible for the Earth's ozone layer?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Ozone"], ca: "Ozone"),
            Question(q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "What is the largest species of shark?", a: ["Tiger Shark", "Great White Shark", "Hammerhead Shark", "Whale Shark"], ca: "Whale Shark"),
            Question(q: "In what year did the Titanic sink?", a: ["1907", "1912", "1921", "1935"], ca: "1912"),
            Question(q: "Which planet is often referred to as the 'Red Planet'?", a: ["Earth", "Mars", "Jupiter", "Saturn"], ca: "Mars"),
            Question(q: "Who is the author of the 'Harry Potter' book series?", a: ["J.K. Rowling", "George Orwell", "J.R.R. Tolkien", "C.S. Lewis"], ca: "J.K. Rowling"),
            Question(q: "What is the smallest prime number?", a: ["0", "1", "2", "3"], ca: "2"),
            Question(q: "Which country is known as the Land of the Rising Sun?", a: ["China", "South Korea", "Japan", "Vietnam"], ca: "Japan"),
            Question(q: "What is the largest desert in the world?", a: ["Sahara Desert", "Arabian Desert", "Gobi Desert", "Antarctica"], ca: "Antarctica"),
            
            Question(q: "Which gas do humans exhale when they breathe?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], ca: "Carbon Dioxide"),
            Question(q: "What is the chemical symbol for the element hydrogen?", a: ["H", "He", "Hy", "Ho"], ca: "H"),
            Question(q: "How many bones are there in the adult human body?", a: ["106", "206", "306", "406"], ca: "206"),
            Question(q: "Who is known as the 'Father of Modern Science'?", a: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nicolaus Copernicus"], ca: "Galileo Galilei"),
            Question(q: "What is the largest species of penguin?", a: ["Emperor Penguin", "King Penguin", "Gentoo Penguin", "Adélie Penguin"], ca: "Emperor Penguin"),
            Question(q: "In which year did World War II end?", a: ["1943", "1945", "1947", "1950"], ca: "1945"),
            Question(q: "What is the primary function of the human heart?", a: ["Pumping Blood", "Digesting Food", "Filtering Waste", "Producing Hormones"], ca: "Pumping Blood"),
            Question(q: "Which planet is known as the 'Evening Star'?", a: ["Mars", "Venus", "Jupiter", "Saturn"], ca: "Venus"),
            Question(q: "Who painted the 'Mona Lisa'?", a: ["Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Michelangelo"], ca: "Leonardo da Vinci"),
            Question(q: "What is the currency of Japan?", a: ["Yuan", "Yen", "Won", "Dollar"], ca: "Yen"),
            
            Question(q: "What is the boiling point of water in Celsius?", a: ["0°C", "32°C", "100°C", "212°C"], ca: "100°C"),
            Question(q: "Which gas is commonly known as laughing gas?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Nitrous Oxide"], ca: "Nitrous Oxide"),
            Question(q: "Who wrote the novel '1984'?", a: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "F. Scott Fitzgerald"], ca: "George Orwell"),
            Question(q: "What is the largest bird in the world?", a: ["Eagle", "Ostrich", "Albatross", "Condor"], ca: "Ostrich"),
            Question(q: "In what year did the Apollo 11 mission land the first humans on the moon?", a: ["1962", "1967", "1969", "1973"], ca: "1969"),
            Question(q: "What is the chemical symbol for the element helium?", a: ["He", "H", "Hi", "Hm"], ca: "He"),
            Question(q: "Who wrote 'The Odyssey'?", a: ["Homer", "Virgil", "Dante", "Plato"], ca: "Homer"),
            Question(q: "Which gas is responsible for the greenhouse effect on Earth?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"], ca: "Carbon Dioxide"),
            Question(q: "What is the largest snake in the world?", a: ["Python", "Cobra", "Anaconda", "Viper"], ca: "Anaconda"),
            Question(q: "What is the tallest mountain on Earth?", a: ["K2", "Mount Everest", "Mount Kilimanjaro", "Mount McKinley"], ca: "Mount Everest"),
        Question(q: "What is the smallest planet in our solar system?", a: ["Mercury", "Venus", "Mars", "Pluto"], ca: "Mercury"),
            Question(q: "Who wrote 'Pride and Prejudice'?", a: ["Jane Austen", "Charles Dickens", "Emily Brontë", "F. Scott Fitzgerald"], ca: "Jane Austen"),
            Question(q: "What is the chemical symbol for the element nitrogen?", a: ["Nt", "Ni", "N", "No"], ca: "N"),
            Question(q: "How many legs does a spider typically have?", a: ["4", "6", "8", "10"], ca: "8"),
            Question(q: "Which gas is responsible for the Northern Lights (Aurora Borealis)?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], ca: "Nitrogen"),
            Question(q: "Who is the author of 'The Great Gatsby'?", a: ["F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain", "Harper Lee"], ca: "F. Scott Fitzgerald"),
            Question(q: "What is the largest land animal on Earth?", a: ["African Elephant", "Giraffe", "Hippopotamus", "Rhinoceros"], ca: "African Elephant"),
            Question(q: "In what year did the Berlin Wall fall?", a: ["1961", "1985", "1989", "1991"], ca: "1989"),
            Question(q: "What is the primary gas that makes up the Sun?", a: ["Oxygen", "Helium", "Hydrogen", "Carbon"], ca: "Hydrogen"),
            Question(q: "Who wrote the play 'Romeo and Juliet'?", a: ["Charles Dickens", "Jane Austen", "William Shakespeare", "F. Scott Fitzgerald"], ca: "William Shakespeare"),
            Question(q: "What is the chemical symbol for the element silicon?", a: ["Si", "Sl", "Se", "So"], ca: "Si"),
            Question(q: "What is the largest moon in our solar system?", a: ["Io", "Europa", "Titan", "Ganymede"], ca: "Ganymede"),
            Question(q: "How many continents are there on Earth?", a: ["3", "5", "7", "9"], ca: "7"),
            Question(q: "What is the freezing point of water in Celsius?", a: ["0°C", "32°C", "100°C", "212°C"], ca: "0°C"),
            Question(q: "Which gas do humans exhale when they breathe?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], ca: "Carbon Dioxide"),
            Question(q: "Who was the first woman to win a Nobel Prize?", a: ["Marie Curie", "Rosa Parks", "Amelia Earhart", "Indira Gandhi"], ca: "Marie Curie"),
            Question(q: "What is the chemical symbol for the element iron?", a: ["In", "Ir", "Fe", "Fr"], ca: "Fe"),
            Question(q: "How many bones are there in the adult human body?", a: ["106", "206", "306", "406"], ca: "206"),
            Question(q: "Who is known as the 'Father of Modern Science'?", a: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nicolaus Copernicus"], ca: "Galileo Galilei"),
            Question(q: "What is the largest species of penguin?", a: ["Emperor Penguin", "King Penguin", "Gentoo Penguin", "Adélie Penguin"], ca: "Emperor Penguin"),
        Question(q: "What is the largest desert in Africa?", a: ["Sahara Desert", "Kalahari Desert", "Namib Desert", "Gobi Desert"], ca: "Sahara Desert"),
            Question(q: "Who was the first woman to fly solo nonstop across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "What is the chemical symbol for the element calcium?", a: ["Ca", "Ce", "Cm", "Co"], ca: "Ca"),
            Question(q: "How many players are there on a standard soccer (football) team?", a: ["8", "9", "10", "11"], ca: "11"),
            Question(q: "Which gas is known as 'laughing gas'?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Nitrous Oxide"], ca: "Nitrous Oxide"),
            Question(q: "Who wrote the novel 'To Kill a Mockingbird'?", a: ["F. Scott Fitzgerald", "Mark Twain", "Harper Lee", "J.D. Salinger"], ca: "Harper Lee"),
            Question(q: "What is the largest planet in our solar system by volume?", a: ["Earth", "Mars", "Jupiter", "Saturn"], ca: "Jupiter"),
            Question(q: "In what year did Christopher Columbus reach the Americas?", a: ["1492", "1507", "1513", "1521"], ca: "1492"),
            Question(q: "Which gas is the most abundant in Earth's atmosphere?", a: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], ca: "Nitrogen"),
            Question(q: "Who is the author of 'War and Peace'?", a: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"], ca: "Leo Tolstoy"),
            Question(q: "What is the chemical symbol for the element potassium?", a: ["K", "Km", "Ke", "Ka"], ca: "K"),
            Question(q: "How many teeth does an adult human typically have?", a: ["20", "28", "32", "36"], ca: "32"),
            Question(q: "Which planet in our solar system is known for its beautiful rings?", a: ["Venus", "Mars", "Jupiter", "Saturn"], ca: "Saturn"),
            Question(q: "What is the largest type of whale?", a: ["Blue Whale", "Humpback Whale", "Killer Whale", "Sperm Whale"], ca: "Blue Whale"),
            Question(q: "In which year did the United States declare independence from Britain?", a: ["1763", "1776", "1789", "1801"], ca: "1776"),
            Question(q: "What is the chemical symbol for the element sodium?", a: ["So", "Sd", "Na", "No"], ca: "Na"),
            Question(q: "How many chambers are there in the human heart?", a: ["2", "3", "4", "5"], ca: "4"),
            Question(q: "Who wrote the novel 'The Catcher in the Rye'?", a: ["J.K. Rowling", "George Orwell", "J.D. Salinger", "F. Scott Fitzgerald"], ca: "J.D. Salinger"),
            Question(q: "What is the national flower of Japan?", a: ["Cherry Blossom", "Rose", "Sunflower", "Tulip"], ca: "Cherry Blossom"),
            Question(q: "Which gas is commonly used in balloons to make them float?", a: ["Oxygen", "Carbon Dioxide", "Helium", "Nitrogen"], ca: "Helium"),
        Question(q: "Who is considered the greatest basketball player of all time?", a: ["Michael Jordan", "LeBron James", "Kobe Bryant", "Magic Johnson"], ca: "Michael Jordan"),
            Question(q: "In which sport is a 'hat-trick' commonly used to describe three consecutive goals by a player?", a: ["Soccer", "Cricket", "Hockey", "Tennis"], ca: "Cricket"),
            Question(q: "What is the term for a perfect score in bowling?", a: ["Strike", "Spare", "Turkey", "300"], ca: "300"),
            Question(q: "Which country has won the most FIFA World Cup titles?", a: ["Germany", "Argentina", "Brazil", "Italy"], ca: "Brazil"),
            Question(q: "Who is the most decorated Olympian of all time, with 28 Olympic medals?", a: ["Usain Bolt", "Michael Phelps", "Simone Biles", "Carl Lewis"], ca: "Michael Phelps"),
            Question(q: "What sport is known as the 'king of sports'?", a: ["Soccer", "Cricket", "Tennis", "Golf"], ca: "Soccer"),
            Question(q: "Which country is famous for inventing the sport of cricket?", a: ["India", "Australia", "England", "South Africa"], ca: "England"),
            Question(q: "Who holds the record for the most home runs in a single MLB season?", a: ["Babe Ruth", "Barry Bonds", "Mark McGwire", "Sammy Sosa"], ca: "Barry Bonds"),
            Question(q: "What is the fastest recorded speed for a tennis serve in miles per hour?", a: ["120 mph", "140 mph", "160 mph", "180 mph"], ca: "163.7 mph"),
            Question(q: "Which sport uses the term 'birdie' and 'eagle' to describe scores?", a: ["Golf", "Tennis", "Badminton", "Cricket"], ca: "Golf"),

            Question(q: "Who is the all-time leading scorer in NBA history?", a: ["Kareem Abdul-Jabbar", "LeBron James", "Kobe Bryant", "Michael Jordan"], ca: "Kareem Abdul-Jabbar"),
            Question(q: "What is the term for a score of one under par on a golf hole?", a: ["Par", "Birdie", "Eagle", "Bogey"], ca: "Birdie"),
            Question(q: "Which country won the first Rugby World Cup in 1987?", a: ["New Zealand", "Australia", "England", "South Africa"], ca: "New Zealand"),
            Question(q: "What is the name of the famous horse race held annually in Kentucky, USA?", a: ["Belmont Stakes", "Preakness Stakes", "Kentucky Derby", "Grand National"], ca: "Kentucky Derby"),
            Question(q: "In which sport would you perform a slam dunk?", a: ["Basketball", "Volleyball", "Tennis", "Badminton"], ca: "Basketball"),
            Question(q: "What is the total number of players on a standard soccer (football) team, including substitutes?", a: ["8", "9", "10", "11"], ca: "11"),
            Question(q: "Who is the only boxer to win world titles in eight different weight classes?", a: ["Floyd Mayweather Jr.", "Mike Tyson", "Muhammad Ali", "Sugar Ray Leonard"], ca: "Manny Pacquiao"),
            Question(q: "Which sport is known as 'the sport of kings'?", a: ["Polo", "Horse Racing", "Cricket", "Tennis"], ca: "Horse Racing"),
            Question(q: "What is the term for a perfect score in gymnastics?", a: ["10.0", "Perfect Ten", "Gold Score", "Flawless"], ca: "10.0"),
            Question(q: "In which sport do athletes compete for the Claret Jug?", a: ["Tennis", "Golf", "Cricket", "Rugby"], ca: "Golf"),
        Question(q: "What does CPU stand for in computing?", a: ["Central Processing Unit", "Computer Programming Unit", "Control Panel Unit", "Central Program Unit"], ca: "Central Processing Unit"),
            Question(q: "Who is the co-founder of Microsoft Corporation?", a: ["Steve Jobs", "Bill Gates", "Jeff Bezos", "Mark Zuckerberg"], ca: "Bill Gates"),
            Question(q: "Which programming language is known for its use in artificial intelligence and machine learning?", a: ["C++", "Java", "Python", "JavaScript"], ca: "Python"),
            Question(q: "What is the most widely used web browser worldwide?", a: ["Internet Explorer", "Safari", "Firefox", "Google Chrome"], ca: "Google Chrome"),
            Question(q: "What does 'URL' stand for in web technology?", a: ["Uniform Resource Locator", "Universal Reference Link", "Uniform Registry Language", "Universal Resource Link"], ca: "Uniform Resource Locator"),
            Question(q: "Which company developed the Android operating system?", a: ["Google", "Apple", "Microsoft", "Samsung"], ca: "Google"),
            Question(q: "What is the largest social media platform in the world?", a: ["Twitter", "Instagram", "Facebook", "LinkedIn"], ca: "Facebook"),
            Question(q: "Who is known as the co-founder of Apple Inc. alongside Steve Jobs?", a: ["Bill Gates", "Jeff Bezos", "Steve Wozniak", "Mark Zuckerberg"], ca: "Steve Wozniak"),
            Question(q: "What does 'HTML' stand for in web development?", a: ["Hyper Text Markup Language", "High-Level Text Management Language", "Hyperlink and Text Markup Language", "High-Level Text Markup Language"], ca: "Hyper Text Markup Language"),
            Question(q: "Which tech company's headquarters is known as the 'Apple Park' and resembles a spaceship?", a: ["Microsoft", "Google", "Apple", "Amazon"], ca: "Apple"),

            Question(q: "What does 'AI' stand for in the context of technology?", a: ["Artificial Intelligence", "Advanced Interface", "Automated Information", "All-Inclusive"], ca: "Artificial Intelligence"),
            Question(q: "Who is the co-founder of Tesla, Inc.?", a: ["Bill Gates", "Elon Musk", "Jeff Bezos", "Mark Zuckerberg"], ca: "Elon Musk"),
            Question(q: "Which programming language is often used for building mobile apps?", a: ["C++", "Java", "Python", "Swift"], ca: "Swift"),
            Question(q: "What is the name of the virtual assistant developed by Amazon?", a: ["Google Assistant", "Siri", "Cortana", "Alexa"], ca: "Alexa"),
            Question(q: "Which technology company is known for its search engine and advertising platform?", a: ["Apple", "Facebook", "Microsoft", "Google"], ca: "Google"),
            Question(q: "What does 'IoT' stand for in the context of technology?", a: ["Internet of Things", "Information on Technology", "Input/Output Tools", "Innovative Online Technology"], ca: "Internet of Things"),
            Question(q: "Who is the CEO of Facebook as of 2023?", a: ["Mark Zuckerberg", "Tim Cook", "Sundar Pichai", "Jeff Bezos"], ca: "Mark Zuckerberg"),
            Question(q: "Which programming language was created by Guido van Rossum and is known for its readability and simplicity?", a: ["Java", "C++", "Python", "Ruby"], ca: "Python"),
            Question(q: "What is the name of the first artificial satellite launched into space by the Soviet Union in 1957?", a: ["Explorer 1", "Apollo 11", "Sputnik 1", "Hubble Space Telescope"], ca: "Sputnik 1"),
            Question(q: "What does 'VPN' stand for in the context of internet security?", a: ["Virtual Personal Network", "Visual Privacy Network", "Virus Protection Network", "Virtual Private Network"], ca: "Virtual Private Network"),
        Question(q: "What is the main function of a firewall in computer security?", a: ["Detect viruses", "Filter network traffic", "Optimize computer performance", "Create backups"], ca: "Filter network traffic"),
           Question(q: "What is the term for a software program that replicates itself and spreads to other computers?", a: ["Virus", "Firewall", "Spam", "Malware"], ca: "Virus"),
           Question(q: "What is the largest social media platform primarily used for professional networking?", a: ["Facebook", "Twitter", "Instagram", "LinkedIn"], ca: "LinkedIn"),
           Question(q: "Which tech company is known for its gaming platform and game development tools, including Unity Engine?", a: ["Epic Games", "Electronic Arts", "Ubisoft", "Unity Technologies"], ca: "Unity Technologies"),
           Question(q: "What is the term for the process of converting spoken language into written text by a computer program?", a: ["Translation", "Transcription", "Transmutation", "Transfiguration"], ca: "Transcription"),
           Question(q: "Which technology company developed the Windows operating system?", a: ["Apple", "Microsoft", "Google", "Amazon"], ca: "Microsoft"),
           Question(q: "What does 'AI' stand for in the context of technology?", a: ["Artificial Intelligence", "Advanced Interface", "Automated Information", "All-Inclusive"], ca: "Artificial Intelligence"),
           Question(q: "Which tech company is known for its electric vehicles (EVs) and the Model S, Model 3, Model X, and Model Y?", a: ["Ford", "Toyota", "Tesla", "Volkswagen"], ca: "Tesla"),
           Question(q: "What is the term for a program that appears to be legitimate but performs malicious actions on a computer?", a: ["Firewall", "Antivirus", "Adware", "Trojan Horse"], ca: "Trojan Horse"),
           Question(q: "In the context of cybersecurity, what does 'DDoS' stand for?", a: ["Distributed Data Storage", "Digital Defense of Systems", "Distributed Denial of Service", "Data Development and Security"], ca: "Distributed Denial of Service"),

           Question(q: "What is the primary function of a CPU in a computer?", a: ["Display graphics", "Store data", "Perform calculations", "Connect to the internet"], ca: "Perform calculations"),
           Question(q: "Which programming language is often used for building mobile apps?", a: ["C++", "Java", "Python", "Swift"], ca: "Swift"),
           Question(q: "What is the name of the virtual assistant developed by Apple?", a: ["Google Assistant", "Siri", "Cortana", "Alexa"], ca: "Siri"),
           Question(q: "What is the name of the first commercially successful video game?", a: ["Pong", "Space Invaders", "Pac-Man", "Super Mario Bros."], ca: "Pong"),
           Question(q: "What does 'URL' stand for in web technology?", a: ["Uniform Resource Locator", "Universal Reference Link", "Uniform Registry Language", "Universal Resource Link"], ca: "Uniform Resource Locator"),
           Question(q: "Which company is known for its gaming consoles, including the PlayStation series?", a: ["Microsoft", "Sony", "Nintendo", "Sega"], ca: "Sony"),
           Question(q: "Who is the co-founder of Amazon?", a: ["Bill Gates", "Elon Musk", "Jeff Bezos", "Mark Zuckerberg"], ca: "Jeff Bezos"),
           Question(q: "What is the term for a person who gains unauthorized access to computer systems for malicious purposes?", a: ["Hacker", "Coder", "Programmer", "Analyst"], ca: "Hacker"),
           Question(q: "Which technology company is known for its search engine and advertising platform?", a: ["Apple", "Facebook", "Microsoft", "Google"], ca: "Google"),
           Question(q: "What is the largest planet in our solar system by volume?", a: ["Earth", "Mars", "Jupiter", "Saturn"], ca: "Jupiter"),
           Question(q: "What is the term for a software program that provides security by monitoring and filtering network traffic?", a: ["Firewall", "Antivirus", "Spam", "Malware"], ca: "Firewall"),

           Question(q: "What is the term for a computer program that displays advertisements to users and may collect their data without consent?", a: ["Virus", "Firewall", "Spam", "Adware"], ca: "Adware"),
           Question(q: "Who is the co-founder of Tesla, Inc.?", a: ["Bill Gates", "Elon Musk", "Jeff Bezos", "Mark Zuckerberg"], ca: "Elon Musk"),
           Question(q: "What is the name of the highest-speed internet connection commonly available to consumers?", a: ["Broadband", "DSL", "Dial-up", "Fiber Optic"], ca: "Fiber Optic"),
           Question(q: "Which programming language was created by Guido van Rossum and is known for its readability and simplicity?", a: ["Java", "C++", "Python", "Ruby"], ca: "Python"),
           Question(q: "What is the name of the first artificial satellite launched into space by the Soviet Union in 1957?", a: ["Explorer 1", "Apollo 11", "Sputnik 1", "Hubble Space Telescope"], ca: "Sputnik 1"),
           Question(q: "What does 'VPN' stand for in the context of internet security?", a: ["Virtual Personal Network", "Visual Privacy Network", "Virus Protection Network", "Virtual Private Network"], ca: "Virtual Private Network"),
           Question(q: "Which company developed the Android operating system?", a: ["Google", "Apple", "Microsoft", "Samsung"], ca: "Google"),
           Question(q: "What is the term for a type of computer malware that encrypts files and demands a ransom for their release?", a: ["Spyware", "Adware", "Trojan Horse", "Ransomware"], ca: "Ransomware"),
           Question(q: "In the context of computer graphics, what does 'GPU' stand for?", a: ["Graphics Processing Unit", "General Processing Unit", "Graphical Presentation Unit", "Geographical Positioning Unit"], ca: "Graphics Processing Unit"),
           Question(q: "What is the name of the first web browser developed by Tim Berners-Lee?", a: ["Internet Explorer", "Netscape Navigator", "Mozilla Firefox", "Google Chrome"], ca: "Netscape Navigator"),
        Question(q: "Who played the role of Tony Stark/Iron Man in the Marvel Cinematic Universe?", a: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"], ca: "Robert Downey Jr."),
           Question(q: "Which film won the Academy Award for Best Picture in 1994, directed by Robert Zemeckis?", a: ["Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "Schindler's List"], ca: "Forrest Gump"),
           Question(q: "What is the name of the fictional wizarding school in the 'Harry Potter' film series?", a: ["Hogwarts School of Witchcraft and Wizardry", "Durmstrang Institute", "Beauxbatons Academy of Magic", "Ilvermorny School of Witchcraft and Wizardry"], ca: "Hogwarts School of Witchcraft and Wizardry"),
           Question(q: "Who directed the 1975 film 'Jaws'?", a: ["Martin Scorsese", "Francis Ford Coppola", "George Lucas", "Steven Spielberg"], ca: "Steven Spielberg"),
           Question(q: "Which actor portrayed the character of Jack Dawson in the film 'Titanic'?", a: ["Leonardo DiCaprio", "Brad Pitt", "Johnny Depp", "Tom Hanks"], ca: "Leonardo DiCaprio"),
           Question(q: "Which animated film features a young lion named Simba as the main character?", a: ["The Little Mermaid", "Aladdin", "Beauty and the Beast", "The Lion King"], ca: "The Lion King"),
           Question(q: "In the film 'The Lord of the Rings: The Fellowship of the Ring,' who played the role of Frodo Baggins?", a: ["Elijah Wood", "Daniel Radcliffe", "Rupert Grint", "Orlando Bloom"], ca: "Elijah Wood"),
           Question(q: "What is the name of the ship that sank in the 1997 film 'Titanic'?", a: ["Carpathia", "Lusitania", "Olympic", "RMS Titanic"], ca: "RMS Titanic"),
           Question(q: "Which actress starred as Elle Woods in the film 'Legally Blonde'?", a: ["Reese Witherspoon", "Jennifer Aniston", "Cameron Diaz", "Kate Winslet"], ca: "Reese Witherspoon"),
           Question(q: "In the movie 'Star Wars: Episode IV - A New Hope,' who played the role of Princess Leia?", a: ["Carrie Fisher", "Natalie Portman", "Keira Knightley", "Daisy Ridley"], ca: "Carrie Fisher"),

           Question(q: "Which film directed by Quentin Tarantino features characters Jules Winnfield and Vincent Vega?", a: ["Reservoir Dogs", "Pulp Fiction", "Kill Bill", "Inglourious Basterds"], ca: "Pulp Fiction"),
           Question(q: "What is the title of the third film in Christopher Nolan's Batman trilogy?", a: ["The Dark Knight Rises", "The Dark Knight Returns", "Batman Forever", "Batman & Robin"], ca: "The Dark Knight Rises"),
           Question(q: "Which film won the Academy Award for Best Animated Feature in 2013, featuring a character named Anna?", a: ["Frozen", "Moana", "Tangled", "Brave"], ca: "Frozen"),
           Question(q: "In 'The Matrix' film series, what is the real name of the character known as Neo?", a: ["John Anderson", "Thomas Anderson", "David Anderson", "William Anderson"], ca: "Thomas Anderson"),
           Question(q: "Who directed the 1993 science fiction film 'Jurassic Park'?", a: ["Steven Spielberg", "James Cameron", "George Lucas", "Ridley Scott"], ca: "Steven Spielberg"),
           Question(q: "What is the name of the fictional African country featured in the film 'Black Panther'?", a: ["Zamunda", "Wakanda", "Genovia", "Elbonia"], ca: "Wakanda"),
           Question(q: "Who played the character of Hermione Granger in the 'Harry Potter' film series?", a: ["Emma Watson", "Emma Stone", "Emma Roberts", "Emma Thompson"], ca: "Emma Watson"),
           Question(q: "Which actor starred as the iconic secret agent James Bond in the 2006 film 'Casino Royale'?", a: ["Pierce Brosnan", "Roger Moore", "Timothy Dalton", "Daniel Craig"], ca: "Daniel Craig"),
           Question(q: "In the film 'The Wizard of Oz,' what color is the Wicked Witch of the West?", a: ["Green", "Red", "Blue", "Black"], ca: "Green"),
           Question(q: "Which actor portrayed the character of Tony Montana in the film 'Scarface'?", a: ["Al Pacino", "Robert De Niro", "Joe Pesci", "Johnny Depp"], ca: "Al Pacino"),

           Question(q: "What is the title of the first 'Toy Story' film released in 1995?", a: ["Toy Story", "Toy Story 2", "Toy Story 3", "Toy Story 4"], ca: "Toy Story"),
           Question(q: "Who directed the 1982 science fiction film 'Blade Runner'?", a: ["James Cameron", "George Lucas", "Ridley Scott", "Steven Spielberg"], ca: "Ridley Scott"),
           Question(q: "In the movie 'Inception,' what is the device used to enter and navigate dreams?", a: ["Dream Machine", "Time Machine", "Reality Alterer", "Dream Navigator"], ca: "Dream Machine"),
           Question(q: "Which actress starred as Katniss Everdeen in 'The Hunger Games' film series?", a: ["Jennifer Aniston", "Scarlett Johansson", "Emma Watson", "Jennifer Lawrence"], ca: "Jennifer Lawrence"),
           Question(q: "What is the title of the film directed by James Cameron that became the highest-grossing movie of all time?", a: ["Titanic", "Avatar", "Jurassic Park", "Star Wars: The Force Awakens"], ca: "Avatar"),
           Question(q: "Which film features a character named Jason Bourne, portrayed by Matt Damon?", a: ["Mission: Impossible", "Die Hard", "The Bourne Identity", "Taken"], ca: "The Bourne Identity"),
           Question(q: "Who played the role of Aragorn in 'The Lord of the Rings' film trilogy?", a: ["Sean Connery", "Liam Neeson", "Viggo Mortensen", "Orlando Bloom"], ca: "Viggo Mortensen"),
           Question(q: "What is the name of the fictional African country featured in the film 'Coming to America'?", a: ["Wakanda", "Zamunda", "Genovia", "Elbonia"], ca: "Zamunda"),
           Question(q: "Who directed the 1977 space opera film 'Star Wars'?", a: ["Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"], ca: "George Lucas"),
           Question(q: "In the film 'The Matrix,' what is the primary color associated with the virtual world?", a: ["Red", "Blue", "Green", "Black"], ca: "Green"),

           Question(q: "Which film features a character named Don Vito Corleone, portrayed by Marlon Brando?", a: ["Goodfellas", "Scarface", "The Godfather", "Heat"], ca: "The Godfather"),
           Question(q: "What is the name of the fictional wizarding school in the 'Harry Potter' film series?", a: ["Hogwarts School of Witchcraft and Wizardry", "Durmstrang Institute", "Beauxbatons Academy of Magic", "Ilvermorny School of Witchcraft and Wizardry"], ca: "Hogwarts School of Witchcraft and Wizardry"),
           Question(q: "Who played the role of Neo in 'The Matrix' film series?", a: ["Keanu Reeves", "Tom Cruise", "Will Smith", "Brad Pitt"], ca: "Keanu Reeves"),
           Question(q: "What is the title of the 1985 adventure film directed by Richard Donner, featuring a group of kids searching for treasure?", a: ["The Goonies", "Stand by Me", "E.T. the Extra-Terrestrial", "The Sandlot"], ca: "The Goonies"),
           Question(q: "In the film 'Jurassic Park,' what is the name of the island where the dinosaur theme park is located?", a: ["Isla Sorna", "Isla Nublar", "Isla Muerta", "Isla Pena"], ca: "Isla Nublar"),
           Question(q: "Who played the role of Katniss Everdeen in 'The Hunger Games' film series?", a: ["Jennifer Aniston", "Scarlett Johansson", "Emma Watson", "Jennifer Lawrence"], ca: "Jennifer Lawrence"),
           Question(q: "Which actor portrayed the character of Harry Potter in the 'Harry Potter' film series?", a: ["Daniel Radcliffe", "Rupert Grint", "Elijah Wood", "Tom Felton"], ca: "Daniel Radcliffe"),
           Question(q: "What is the name of the fictional African country featured in the film 'Black Panther'?", a: ["Wakanda", "Zamunda", "Genovia", "Elbonia"], ca: "Wakanda"),
           Question(q: "Who directed the 1994 film 'Pulp Fiction'?", a: ["Martin Scorsese", "Francis Ford Coppola", "George Lucas", "Quentin Tarantino"], ca: "Quentin Tarantino"),
           Question(q: "What is the title of the first film in the 'Star Wars' franchise, released in 1977?", a: ["Star Wars: Episode IV - A New Hope", "Star Wars: Episode V - The Empire Strikes Back", "Star Wars: Episode VI - Return of the Jedi", "Star Wars: Episode I - The Phantom Menace"], ca: "Star Wars: Episode IV - A New Hope"),

           Question(q: "Which film directed by Christopher Nolan features a character named Dom Cobb, portrayed by Leonardo DiCaprio?", a: ["Inception", "Interstellar", "Dunkirk", "The Prestige"], ca: "Inception"),
           Question(q: "What is the title of the 2003 film directed by Peter Jackson, based on J.R.R. Tolkien's fantasy novel?", a: ["The Hobbit", "The Lord of the Rings: The Fellowship of the Ring", "The Chronicles of Narnia", "Eragon"], ca: "The Lord of the Rings: The Fellowship of the Ring"),
           Question(q: "Who played the character of Captain Jack Sparrow in the 'Pirates of the Caribbean' film series?", a: ["Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Keira Knightley"], ca: "Johnny Depp"),
           Question(q: "In the film 'The Silence of the Lambs,' who played the role of Dr. Hannibal Lecter?", a: ["Anthony Hopkins", "Liam Neeson", "Morgan Freeman", "Jack Nicholson"], ca: "Anthony Hopkins"),
           Question(q: "Which film won the Academy Award for Best Animated Feature in 2001, featuring a character named Shrek?", a: ["Finding Nemo", "Shrek", "The Incredibles", "Toy Story 2"], ca: "Shrek"),
           Question(q: "What is the title of the 1984 science fiction film directed by James Cameron, featuring a character named Sarah Connor?", a: ["The Terminator", "Predator", "Aliens", "RoboCop"], ca: "The Terminator"),
           Question(q: "Who directed the 2009 science fiction film 'Avatar'?", a: ["Steven Spielberg", "James Cameron", "George Lucas", "Christopher Nolan"], ca: "James Cameron"),
           Question(q: "Which film features a character named Maximus Decimus Meridius, portrayed by Russell Crowe?", a: ["Gladiator", "Troy", "300", "Braveheart"], ca: "Gladiator"),
           Question(q: "What is the name of the fictional African country featured in the film 'Coming to America'?", a: ["Wakanda", "Zamunda", "Genovia", "Elbonia"], ca: "Zamunda"),
           Question(q: "Who played the role of Tony Stark/Iron Man in the Marvel Cinematic Universe?", a: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"], ca: "Robert Downey Jr."),
        Question(q: "Who was the first President of the United States?", a: ["John Adams", "Benjamin Franklin", "Thomas Jefferson", "George Washington"], ca: "George Washington"),
            Question(q: "Which Egyptian queen is known for her relationships with Julius Caesar and Mark Antony?", a: ["Cleopatra", "Nefertiti", "Hatshepsut", "Nefertari"], ca: "Cleopatra"),
            Question(q: "In which year did Christopher Columbus first reach the Americas?", a: ["1492", "1501", "1520", "1498"], ca: "1492"),
            Question(q: "Who was the first woman to fly solo across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "Which European explorer is credited with discovering the sea route to India in the late 15th century?", a: ["Marco Polo", "Vasco da Gama", "Christopher Columbus", "Amerigo Vespucci"], ca: "Vasco da Gama"),
            Question(q: "Who wrote the 'The Communist Manifesto' along with Friedrich Engels?", a: ["Karl Marx", "Vladimir Lenin", "Leon Trotsky", "Joseph Stalin"], ca: "Karl Marx"),
            Question(q: "What year did World War II end?", a: ["1943", "1945", "1947", "1950"], ca: "1945"),
            Question(q: "Which ancient civilization built the Great Wall of China?", a: ["Egyptians", "Romans", "Greeks", "Chinese"], ca: "Chinese"),
            Question(q: "Who was the first woman to win a Nobel Prize and remains the only person to win Nobel Prizes in two different scientific fields?", a: ["Marie Curie", "Rosalind Franklin", "Jane Goodall", "Dorothy Crowfoot Hodgkin"], ca: "Marie Curie"),
            Question(q: "What major event occurred on July 20, 1969, when astronauts Neil Armstrong and Buzz Aldrin made history?", a: ["The Boston Tea Party", "The Berlin Wall Fall", "The Moon Landing", "The Cuban Missile Crisis"], ca: "The Moon Landing"),

            Question(q: "Who was the first Emperor of Rome?", a: ["Julius Caesar", "Augustus", "Nero", "Caligula"], ca: "Augustus"),
            Question(q: "What was the name of the ship that carried the Pilgrims to America in 1620?", a: ["Mayflower", "Santa Maria", "Nina", "Pinta"], ca: "Mayflower"),
            Question(q: "Which battle is often considered the turning point of the American Civil War?", a: ["Battle of Gettysburg", "Battle of Antietam", "Battle of Bull Run", "Battle of Shiloh"], ca: "Battle of Gettysburg"),
            Question(q: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", a: ["Vladimir Putin", "Joseph Stalin", "Nikita Khrushchev", "Mikhail Gorbachev"], ca: "Nikita Khrushchev"),
            Question(q: "Which famous document was signed by King John of England in 1215 and is considered a cornerstone of constitutional law?", a: ["Magna Carta", "Declaration of Independence", "Bill of Rights", "Emancipation Proclamation"], ca: "Magna Carta"),
            Question(q: "Who was the first woman to fly solo nonstop across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "In which year did the United States declare its independence from Great Britain?", a: ["1756", "1776", "1789", "1801"], ca: "1776"),
            Question(q: "Which English scientist is known for formulating the laws of motion and universal gravitation?", a: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Charles Darwin"], ca: "Isaac Newton"),
            Question(q: "Who was the first President of the United States?", a: ["John Adams", "Benjamin Franklin", "Thomas Jefferson", "George Washington"], ca: "George Washington"),
            Question(q: "What major event took place on April 15, 1912, involving the sinking of a famous passenger ship?", a: ["Attack on Pearl Harbor", "The Hindenburg Disaster", "The Titanic Sinking", "D-Day"], ca: "The Titanic Sinking"),

            Question(q: "Who was the famous leader of the Indian independence movement against British colonial rule?", a: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"], ca: "Mahatma Gandhi"),
            Question(q: "In which year did the United States formally annex the Hawaiian Islands?", a: ["1842", "1867", "1898", "1905"], ca: "1898"),
            Question(q: "Which ancient civilization is known for building the Pyramids of Giza?", a: ["Maya", "Inca", "Aztec", "Egyptian"], ca: "Egyptian"),
            Question(q: "Who was the first woman to serve as the Prime Minister of the United Kingdom?", a: ["Margaret Thatcher", "Theresa May", "Angela Merkel", "Jacinda Ardern"], ca: "Margaret Thatcher"),
            Question(q: "Which famous African-American civil rights leader delivered the 'I Have a Dream' speech during the March on Washington in 1963?", a: ["Malcolm X", "Medgar Evers", "Rosa Parks", "Martin Luther King Jr."], ca: "Martin Luther King Jr."),
            Question(q: "What is the name of the ancient Roman gladiatorial arena located in the heart of Rome?", a: ["Colosseum", "Pantheon", "Forum Romanum", "Circus Maximus"], ca: "Colosseum"),
            Question(q: "Who was the first woman to fly solo nonstop across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "Which European explorer is credited with discovering the sea route to India in the late 15th century?", a: ["Marco Polo", "Vasco da Gama", "Christopher Columbus", "Amerigo Vespucci"], ca: "Vasco da Gama"),
            Question(q: "In which year did Christopher Columbus first reach the Americas?", a: ["1492", "1501", "1520", "1498"], ca: "1492"),
            Question(q: "What year did World War II end?", a: ["1943", "1945", "1947", "1950"], ca: "1945"),

            Question(q: "Who was the first Emperor of Rome?", a: ["Julius Caesar", "Augustus", "Nero", "Caligula"], ca: "Augustus"),
            Question(q: "What was the name of the ship that carried the Pilgrims to America in 1620?", a: ["Mayflower", "Santa Maria", "Nina", "Pinta"], ca: "Mayflower"),
            Question(q: "Which battle is often considered the turning point of the American Civil War?", a: ["Battle of Gettysburg", "Battle of Antietam", "Battle of Bull Run", "Battle of Shiloh"], ca: "Battle of Gettysburg"),
            Question(q: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", a: ["Vladimir Putin", "Joseph Stalin", "Nikita Khrushchev", "Mikhail Gorbachev"], ca: "Nikita Khrushchev"),
            Question(q: "Which famous document was signed by King John of England in 1215 and is considered a cornerstone of constitutional law?", a: ["Magna Carta", "Declaration of Independence", "Bill of Rights", "Emancipation Proclamation"], ca: "Magna Carta"),
            Question(q: "Who was the first woman to fly solo nonstop across the Atlantic Ocean?", a: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], ca: "Amelia Earhart"),
            Question(q: "In which year did the United States declare its independence from Great Britain?", a: ["1756", "1776", "1789", "1801"], ca: "1776"),
            Question(q: "Which English scientist is known for formulating the laws of motion and universal gravitation?", a: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Charles Darwin"], ca: "Isaac Newton"),
            Question(q: "Who was the first President of the United States?", a: ["John Adams", "Benjamin Franklin", "Thomas Jefferson", "George Washington"], ca: "George Washington"),
            Question(q: "What major event took place on April 15, 1912, involving the sinking of a famous passenger ship?", a: ["Attack on Pearl Harbor", "The Hindenburg Disaster", "The Titanic Sinking", "D-Day"], ca: "The Titanic Sinking")
        ]
    
    
}
